default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV["CI"]
    if ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"] && ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"] && ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"]
      app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
        key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
        in_house: false
      )
    end
  end

  desc "Upload metadata + screenshots to App Store Connect"
  lane :upload_listing do
    deliver(
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: false,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      app_review_information: {
        first_name: "Zoe",
        last_name: "Lin",
        phone_number: "+85256660164",
        email_address: "game37qiye@163.com",
        demo_user: "",
        demo_password: "",
        notes: ""
      }
    )
  end

  desc "Upload metadata text only"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: true,
      skip_app_version_update: true,
      force: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      app_review_information: {
        first_name: "Zoe",
        last_name: "Lin",
        phone_number: "+85256660164",
        email_address: "game37qiye@163.com",
        demo_user: "",
        demo_password: "",
        notes: ""
      }
    )
  end

  desc "Upload screenshots only"
  lane :upload_screenshots do
    deliver(
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: false,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false
    )
  end

  desc "Submit the latest TestFlight build for App Store review"
  lane :submit do
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_install: true,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: true,
        export_compliance_uses_encryption: false,
        content_rights_contains_third_party_content: false
      }
    )
  end
end
